# Generated by Django 3.1.4 on 2021-02-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('recompensa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=2021)),
                ('codigoEscola', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='escolas.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Promove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDisciplina', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.disciplina')),
                ('codigoHabilidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Ministra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDisciplina', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.disciplina')),
                ('codigoProfessor', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAluno', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.aluno')),
                ('codigoTurma', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Contem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDisciplina', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.disciplina')),
                ('codigoTurma', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='escolas.turma')),
            ],
        ),
    ]
