# Generated by Django 3.1.5 on 2021-02-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
