# Generated by Django 3.1.5 on 2021-02-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('recompensa', models.CharField(max_length=30)),
            ],
        ),
    ]
